module TradingEdge.ReplaySimulatorV3.Publishers

// Databento publisher_id → venue code lookup. Extracted from
// databento/common/publishers.py. Equity rows only; futures/options publishers
// (1, 20-37, 57-58, 61, 84-85, 97+) are not present.

let venueCode (publisherId: int) : string =
    match publisherId with
    | 2  -> "XNAS"
    | 3  -> "XBOS"
    | 4  -> "XPSX"
    | 5  -> "BATS"
    | 6  -> "BATY"
    | 7  -> "EDGA"
    | 8  -> "EDGX"
    | 9  -> "XNYS"
    | 10 -> "XCIS"
    | 11 -> "XASE"
    | 12 -> "XCHI"
    | 13 -> "XCIS"
    | 14 -> "XCIS"
    | 15 -> "MEMX"
    | 16 -> "EPRL"
    | 17 -> "FINN"
    | 18 -> "FINC"
    | 19 -> "FINY"
    | 38 -> "IEXG"
    | 39 -> "XCHI"
    | 40 -> "XCIS"
    | 41 -> "IEXG"
    | 42 -> "EPRL"
    | 43 -> "ARCX"
    | 44 -> "XNYS"
    | 45 -> "XNYS"
    | 46 -> "XNAS"
    | 47 -> "XNAS"
    | 48 -> "XCHI"
    | 49 -> "XCIS"
    | 50 -> "IEXG"
    | 51 -> "EPRL"
    | 52 -> "XNAS"
    | 53 -> "XNYS"
    | 54 -> "FINN"
    | 55 -> "FINY"
    | 56 -> "FINC"
    | 59 -> "DBEQ"
    | 60 -> "EQUS"
    | 62 -> "XCHI"
    | 63 -> "XCIS"
    | 64 -> "IEXG"
    | 65 -> "EPRL"
    | 66 -> "XNAS"
    | 67 -> "XNYS"
    | 68 -> "FINN"
    | 69 -> "FINY"
    | 70 -> "FINC"
    | 71 -> "BATS"
    | 72 -> "BATY"
    | 73 -> "EDGA"
    | 74 -> "EDGX"
    | 75 -> "XBOS"
    | 76 -> "XPSX"
    | 77 -> "MEMX"
    | 78 -> "XASE"
    | 79 -> "ARCX"
    | 80 -> "LTSE"
    | 81 -> "XNAS"
    | 82 -> "FINN"
    | 83 -> "FINC"
    | 86 -> "XBOS"
    | 87 -> "XPSX"
    | 88 -> "XBOS"
    | 89 -> "XPSX"
    | 90 -> "EQUS"
    | 91 -> "XCIS"
    | 92 -> "XNYS"
    | 93 -> "EQUS"
    | 94 -> "EQUS"
    | 95 -> "EQUS"
    | 96 -> "EQUS"
    | n -> sprintf "P%d" n
